spring:
  datasource:
    url: jdbc:mysql://localhost:3306/rentcarDB?createDatabaseIfNotExist=true
    username: root
    password: gurleen
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
security:
  oauth2:
    resource:
      token-info-uri: http://localhost:8282/oauth/check_token
    client:
      client-id: mobile
      client-secret: pin
        



